[build]
  # Build settings
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  # Environment variables
  NODE_VERSION = "18"

# Redirect rules for una.institute domain
[[redirects]]
  from = "/ar/*"
  to = "/ar/:splat.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/ar/index.html"
  status = 200

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://api.una.institute/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://webrtc.github.io https://cdn.socket.io https://www.google-analytics.com/analytics.js https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/webfonts/; img-src 'self' data: https:; media-src 'self' blob: https:; connect-src 'self' ws: wss: https:; frame-src 'self' https:; frame-ancestors 'none'"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom domain configuration
[context.production]
  command = "echo 'Production build for una.institute'"

[context.deploy-preview]
  command = "echo 'Deploy preview build'"

[context.branch-deploy]
  command = "echo 'Branch deploy build'"
